version: '3'
services:
  zincsearch:
    image: public.ecr.aws/zinclabs/zincsearch:latest
    ports:
      - "4080:4080"
    environment:
      - ZINC_DATA_PATH=/data
      - ZINC_FIRST_ADMIN_USER=admin
      - ZINC_FIRST_ADMIN_PASSWORD=Complexpass#123
    volumes:
      - ./data:/data
    networks:
      - mynetwork
  goapp:
    build: .
    environment:
      - ZINC_DATA_PATH=/data
      - ZINC_FIRST_ADMIN_USER=admin
      - ZINC_FIRST_ADMIN_PASSWORD=Complexpass#123
      - ZINC_API_URL=http://zincsearch:4080
    ports:
      - "8080:8088"
      - "6061:6060"
    volumes:
      - ./app:/go/src/app
    working_dir: /go/src/app/cmd/main
    restart: on-failure
    command: gin -i run main.go
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
