basePath: /
definitions:
  http.EmailData:
    properties:
      content:
        type: string
      date:
        type: string
      from:
        type: string
      subject:
        type: string
      to:
        type: string
      xfrom:
        type: string
      xto:
        type: string
    type: object
  http.QueryParam:
    properties:
      query:
        type: string
    type: object
  http.SearchResult:
    properties:
      EmailsEncontrados:
        type: string
    type: object
  http.SuccessResponse:
    properties:
      message:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /email:
    post:
      consumes:
      - application/json
      description: Store an email entry (It´s an example to add a new email value).
      parameters:
      - description: Email parameters
        in: body
        name: emailData
        required: true
        schema:
          $ref: '#/definitions/http.EmailData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.SuccessResponse'
      summary: Index in zincsearch
      tags:
      - Email
  /query:
    post:
      consumes:
      - application/json
      description: Perform a search based on the given query. Please note that the
        query is a string. Search results
      parameters:
      - description: Search parameters
        in: body
        name: query
        required: true
        schema:
          $ref: '#/definitions/http.QueryParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.SearchResult'
      summary: Search text in zincsearch
      tags:
      - Email
  /zinconection:
    get:
      consumes:
      - application/json
      description: Check connectivity with ZincSearch
      produces:
      - application/json
      responses:
        "200":
          description: La conectividad con ZincSearch esta activa, accede por medio
            de las peticiones HTTP de la api de email
          schema:
            type: string
      summary: verify conectivity with ZincSearch
      tags:
      - ZincSearch
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
